name: Ember Application Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm and bower dependencies
        run: |
          cd <repository-directory>  # Replace with the actual repository directory
          npm install
          npx bower install --allow-root

      - name: Run Ember server
        run: |
          cd <repository-directory>  # Replace with the actual repository directory
          npx ember server

      - name: Display app URL
        run: echo "Visit your app at http://localhost:4200."
