name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Change working directory to www
        run: cd open-etc-pool/www

      - name: Install global dependencies
        run: |
          npm install -g ember-cli@2.9.1
          npm install -g bower

      - name: Install Node.js dependencies
        run: npm install

      - name: Install Bower dependencies
        run: npx bower install

      - name: Build Ember application
        run: npm run build
